### ISSUE TITLE
[v2] Gem::LoadError results in misleading failure

### ISSUE THREAD

**Issue by masukomi** [masukomi/rtest#14]
## rtest output
(rtest is at commit 5b08e32279b47020a040746a6e15fa5127723122 )

```
❯ rtest <path/to/test>:53
Running specs in <path/to/test>:53
..........................................
1: [REDACTED CLASS NAME]#call when <rspec context stuff>
    complains that the account doesn't exist should... do something
Traceback (most recent call last):
	7711: from /Users/kayrhodes/bin/rtest:298:in `<main>'
	7710: from /Users/kayrhodes/workspace/rtest/lib/rtest/runner.rb:14:in `run_and_display_this'
	7709: from /Users/kayrhodes/workspace/rtest/lib/rtest/persisters.rb:13:in `update_record_and_display'
	7708: from /Users/kayrhodes/workspace/rtest/lib/rtest/failure_printer.rb:18:in `display_failures'
	7707: from /Users/kayrhodes/workspace/rtest/lib/rtest/failure_printer.rb:18:in `each_with_index'
	7706: from /Users/kayrhodes/workspace/rtest/lib/rtest/failure_printer.rb:18:in `each'
	7705: from /Users/kayrhodes/workspace/rtest/lib/rtest/failure_printer.rb:19:in `block in display_failures'
	7704: from /Users/kayrhodes/workspace/rtest/lib/rtest/failure_printer.rb:13:in `print'
	 ... 7699 levels...
	   4: from /Users/kayrhodes/workspace/rtest/lib/rtest/print_helpers.rb:52:in `next_split_char'
	   3: from /Users/kayrhodes/workspace/rtest/lib/rtest/print_helpers.rb:52:in `find_all'
	   2: from /Users/kayrhodes/workspace/rtest/lib/rtest/print_helpers.rb:52:in `each'
	   1: from /Users/kayrhodes/workspace/rtest/lib/rtest/print_helpers.rb:52:in `block in next_split_char'
/Users/kayrhodes/workspace/rtest/lib/rtest/print_helpers.rb:52:in `match': stack level too deep (SystemStackError)
```

## rspec output

```
❯ rspec <path/to/test>:53
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      rake (~> 13.0)
      Available/installed versions of this gem:
      - 13.0.6
      - 13.0.1
      - 12.3.3
      unf_ext (>= 0)
      Available/installed versions of this gem:
      - 0.0.8.2
      - 0.0.8
      - 0.0.7.7
      diff-lcs (>= 1.2.0, < 2.0)
      Available/installed versions of this gem:
      - 1.5.0
      - 1.4.4
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.

An error occurred while loading ./engines/payment_processing/spec/services/payment_processing/payment_methods/bank_accounts/operations/list_spec.rb.
Failure/Error: require File.expand_path("../config/environment", __dir__)

Gem::LoadError:
  You have already activated ffi 1.15.5, but your Gemfile requires ffi 1.15.4. Prepending `bundle exec` to your command may solve this.
# ./config/boot.rb:5:in `<top (required)>'
# ./config/application.rb:3:in `require_relative'
# ./config/application.rb:3:in `<top (required)>'
# ./config/environment.rb:4:in `require_relative'
# ./config/environment.rb:4:in `<top (required)>'
# ./spec/rails_helper.rb:7:in `<top (required)>'
# <path/to/spec>:3:in `<top (required)>'
Run options: include {:locations=>{"<path/to/spec>"=>[53]}}

All examples were filtered out

Top 0 slowest examples (0 seconds, 0.0% of total time):

Finished in 0.00002 seconds (files took 0.94179 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by masukomi** [comment]
note to self: code to replicate this is in the `rtest_bug_14` branch on your main work repo. last commit has invocation instructions.
